# Generated by Django 4.1.5 on 2023-02-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0003_rename_full_name_author_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating',
            new_name='user_rating',
        ),
    ]
