# Generated by Django 4.1.5 on 2023-02-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0004_rename_rating_author_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
