# Generated by Django 4.1.5 on 2023-02-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0007_alter_post_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data',
        ),
    ]
