# Generated by Django 4.1.5 on 2023-02-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0009_rename_time_in_post_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='date',
        ),
    ]
