# Generated by Django 4.1.5 on 2023-02-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0010_rename_data_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headline',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
